services:
  dev:
    image: flax-trainer-dev:1.0.0
    build:
      context: .
      args:
        YOUR_UID: ${YOUR_UID}
        YOUR_GID: ${YOUR_GID}
    volumes:
      - ${PWD}:/app
      - ${HOME}/.ssh:/home/user/.ssh
    tty: true